### ISSUE TITLE
one process, my1 to set then other process, my2 to read the same filename get default data

### ISSUE THREAD

**Issue by waertf** [pablobaxter/Harmony#50]
package com.example.my1;

import androidx.appcompat.app.AppCompatActivity;

import android.content.Context;
import android.content.SharedPreferences;
import android.os.Bundle;

import com.frybits.harmony.Harmony;

public class MainActivity extends AppCompatActivity {

    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_main);
        Context context=getApplicationContext();
        SharedPreferences prefs = Harmony.getSharedPreferences(context, "abc");
        prefs.edit().putInt("abc",1).commit();// use apply() also not work
    }
}
///////////////////////////////////////////////////////////////////////////////////////////////////
package com.example.my2;

import androidx.appcompat.app.AppCompatActivity;

import android.content.Context;
import android.content.SharedPreferences;
import android.os.Bundle;
import android.util.Log;

import com.frybits.harmony.Harmony;

public class MainActivity extends AppCompatActivity {

    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_main);
        Context context=getApplicationContext();
        SharedPreferences prefs = Harmony.getSharedPreferences(context, "abc");
        Log.d(getPackageName(), String.valueOf(prefs.getInt("abc",-1)));//get -1 instead of 1

        /*Context context=getApplicationContext();
        SharedPreferences prefs = Harmony.getSharedPreferences(context, "PREF_NAME");
        prefs.edit().putInt("PREF_NAME",1).commit();*/
    }
}
///////////////////////////////////////////////////////////////////////////////////////
using implementation 'com.frybits.harmony:harmony:1.2.2'
test device :android emulator API 34

**Comment by pablobaxter** [comment]
Can you also share an example of your `AndroidManifest.xml` file?

**Comment by waertf** [comment]
> Can you also share an example of your `AndroidManifest.xml` file?

My1 part
/////////////////////
<?xml version="1.0" encoding="utf-8"?>
<manifest xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:tools="http://schemas.android.com/tools">

    <application
        android:allowBackup="true"
        android:dataExtractionRules="@xml/data_extraction_rules"
        android:fullBackupContent="@xml/backup_rules"
        android:icon="@mipmap/ic_launcher"
        android:label="@string/app_name"
        android:roundIcon="@mipmap/ic_launcher_round"
        android:supportsRtl="true"
        android:theme="@style/Theme.My1"
        tools:targetApi="31">
        <activity
            android:name=".MainActivity"
            android:exported="true">
            <intent-filter>
                <action android:name="android.intent.action.MAIN" />

                <category android:name="android.intent.category.LAUNCHER" />
            </intent-filter>
        </activity>
    </application>

</manifest>
///////////////////////////////////////////
My2 part
////////////////////////////////
<?xml version="1.0" encoding="utf-8"?>
<manifest xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:tools="http://schemas.android.com/tools">

    <application
        android:allowBackup="true"
        android:dataExtractionRules="@xml/data_extraction_rules"
        android:fullBackupContent="@xml/backup_rules"
        android:icon="@mipmap/ic_launcher"
        android:label="@string/app_name"
        android:roundIcon="@mipmap/ic_launcher_round"
        android:supportsRtl="true"
        android:theme="@style/Theme.My2"
        tools:targetApi="31">
        <activity
            android:name=".MainActivity"
            android:exported="true">
            <intent-filter>
                <action android:name="android.intent.action.MAIN" />

                <category android:name="android.intent.category.LAUNCHER" />
            </intent-filter>
        </activity>
    </application>

</manifest>

**Comment by pablobaxter** [comment]
Harmony is meant for a single app that uses multiple processes, not for two separate apps sharing preferences. In this case, I would recommend a content provider for your use case.

**Comment by waertf** [comment]
> Harmony is meant for a single app that uses multiple processes, not for two separate apps sharing preferences. In this case, I would recommend a content provider for your use case.

Ok, thanks.
