### ISSUE TITLE
Consider to implement Harmony HMI widgets

### ISSUE THREAD

**Issue by AShuba** [pablobaxter/Harmony#51]
First of all let me say that Harmony preferences idea and implementation is great. I am using it in my Multiprocess app instead of buggy Google's SharedPreferences.

But I think the Harmony lib could be even more useful if it will contain its own HMI widgets for using with standard Android PreferenceScreen. Lets consider Switch preference widget layout below for example

```
<PreferenceScreen
    xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:app="http://schemas.android.com/apk/res-auto">

        <SwitchPreferenceCompat
            app:key="Key"
            app:defaultValue="KeyDefault"/>

</PreferenceScreen>
```

In order to integrate it to Application a lot of boiloperated code must be created (below). But from the other side the Android default SharedPreference requires zero lines of code.

```
public class AppSettingsFragment extends PreferenceFragmentCompat {

    public void onCreatePreferences(Bundle savedInstanceState, String rootKey) {
          SwitchPreferenceCompat pref = findPreference(getString(prefId));
          Preference.OnPreferenceChangeListener preferenceChangeListener = (preference, newValue) -> {
              boolean val = (boolean)newValue;
              Harmony.getSharedPreferences(ctx, APP_PREF_NAME).edit().putBoolean(key, val).commit();
              return true;
          };
          if (pref != null) {
              pref.setOnPreferenceChangeListener(preferenceChangeListener);
              pref.setChecked(AHarmony.getSharedPreferences(ctx, APP_PREF_NAME).getBoolean(key, val));
          }
    }
}
```

If you  miss the code above then Swicth widget will read/write preference value from the Android SharedPreference instead of Harmony preference! Further, for the ListPreference additional SummaryProvider must be implemented otherwise widget summary will be read from the Android SharedPreference instead of Harmony preference. And so on.

So my question is whether do I have wrong understanding of the library design and I use it in a wrong way OR Harmony widgets is a next milestone and will be implemented in the future?

**Comment by pablobaxter** [comment]
Closing this issue as there isn't anything actionable.
