### ISSUE TITLE
Sealed classes are not supported as program classes

### ISSUE THREAD

**Issue by sonvirgo** [pablobaxter/Harmony#59]
AGPBI: {"kind":"error","text":"com.android.tools.r8.internal.YI0: Sealed classes are not supported as program classes","sources":[{"file":"D:\\.gradle\\caches\\transforms-3\\d6371cf646137acdb67ca33b94ce2a9c\\transformed\\jetified-harmony-1.2.6-runtime.jar"}],"tool":"D8"}

**Comment by pablobaxter** [comment]
@sonvirgo Thank you for reporting this. I'll take a look at this bug this week.

**Comment by pablobaxter** [comment]
@sonvirgo, I'm unable to reproduce this issue locally. Can you provide some more information?

Gradle version
AGP version
JDK version
compileSDK version

**Comment by sonvirgo** [comment]
Thank mate for your wonderful modules
But I change from SharedPreferences to Service Binder to handle inter-process communication. Something due to higher API level requirements of your modole, I dont remember exactly, sorry. My app targets Android O.
Have a look at it here https://github.com/sonvirgo/4G-Circumvent/releases
Thank you again.

**Comment by pablobaxter** [comment]
No problem. Closing this thread for now then. If you do choose to use Harmony, feel free to comment here, and we can re-open the issue.
