### ISSUE TITLE
Harmony SharedPreferences database not deleted when app is uninstalled

### ISSUE THREAD

**Issue by malbry** [pablobaxter/Harmony#65]
Unless I'm missing something, when an app is uninstalled the Harmony SharedPreferences data are not deleted along with the app. The data therefore persist on the device. It would be good hygiene to delete the data when the app is uninstalled.

**Comment by pablobaxter** [comment]
The data should be removed when the app is uninstalled, as Harmony saves data in the [app-specific storage](https://developer.android.com/training/data-storage/app-specific). According to the documentation in that page:

> When the user uninstalls your app, the files saved in app-specific storage are removed.

Is it possible that the data is being restored from an app backup (ex. having `allowBackup=true` set in the AndroidManifest)?
